//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.1433
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgrammersInc.Windows.Forms {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProgrammersInc.Windows.Forms.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ArrowDown {
            get {
                object obj = ResourceManager.GetObject("ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowUp {
            get {
                object obj = ResourceManager.GetObject("ArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavigateBar {
            get {
                object obj = ResourceManager.GetObject("NavigateBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NoImage {
            get {
                object obj = ResourceManager.GetObject("NoImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add or Remove Button.
        /// </summary>
        internal static string TEXT_ADD_OR_REMOVE_BUTTON {
            get {
                return ResourceManager.GetString("TEXT_ADD_OR_REMOVE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string TEXT_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("TEXT_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hide.
        /// </summary>
        internal static string TEXT_BUTTON_HIDE {
            get {
                return ResourceManager.GetString("TEXT_BUTTON_HIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Move Down.
        /// </summary>
        internal static string TEXT_BUTTON_MOVE_DOWN {
            get {
                return ResourceManager.GetString("TEXT_BUTTON_MOVE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Move Up.
        /// </summary>
        internal static string TEXT_BUTTON_MOVE_UP {
            get {
                return ResourceManager.GetString("TEXT_BUTTON_MOVE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string TEXT_BUTTON_OK {
            get {
                return ResourceManager.GetString("TEXT_BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset.
        /// </summary>
        internal static string TEXT_BUTTON_RESET {
            get {
                return ResourceManager.GetString("TEXT_BUTTON_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Collapse.
        /// </summary>
        internal static string TEXT_COLLAPSE_BUTTON_COLLAPSE {
            get {
                return ResourceManager.GetString("TEXT_COLLAPSE_BUTTON_COLLAPSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expand.
        /// </summary>
        internal static string TEXT_COLLAPSE_BUTTON_EXPAND {
            get {
                return ResourceManager.GetString("TEXT_COLLAPSE_BUTTON_EXPAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configure Buttons.
        /// </summary>
        internal static string TEXT_CONFIGURE_BUTTONS {
            get {
                return ResourceManager.GetString("TEXT_CONFIGURE_BUTTONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display buttons in this order.
        /// </summary>
        internal static string TEXT_LABEL_ORDER_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_LABEL_ORDER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Navigation Pane Options....
        /// </summary>
        internal static string TEXT_MENU_OPTIONS {
            get {
                return ResourceManager.GetString("TEXT_MENU_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Color Table.
        /// </summary>
        internal static string TEXT_SELECT_COLOR_TABLE {
            get {
                return ResourceManager.GetString("TEXT_SELECT_COLOR_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Fewer Buttons.
        /// </summary>
        internal static string TEXT_SHOW_FEWER_BUTTONS {
            get {
                return ResourceManager.GetString("TEXT_SHOW_FEWER_BUTTONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show More Buttons.
        /// </summary>
        internal static string TEXT_SHOW_MORE_BUTTONS {
            get {
                return ResourceManager.GetString("TEXT_SHOW_MORE_BUTTONS", resourceCulture);
            }
        }
    }
}
